### ISSUE TITLE
APCSA Unit 3 if(true == true)

### ISSUE THREAD

**Issue by bacarpenter** [ajaygandecha/youtube#2]
Hey, I have a question on your section on if/else with Boolean expressions. It goes something like:
```
boolean a = true;
if (a == true){
   //code 
}
```
Isn't it better to use `if(a)` instead, as that's more succinct?

Thanks!

**Comment by ajaygandecha** [comment]
My apologies for the late response! Using `if(a)` is definitely more concise and would be a best practice in coding! In order to make it more understandable for APCS students, I used `if(a == true)` as the if statement header, but you would be correct.
